// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MvcStudyBuddy.Api.Data;

namespace MvcStudyBuddy.Api.Migrations
{
    [DbContext(typeof(MvcStudyBuddyContext))]
    partial class MvcStudyBuddyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("MvcStudyBuddy.Api.Models.Assignment", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Assignment");
                });

            modelBuilder.Entity("MvcStudyBuddy.Api.Models.Todo", b =>
                {
                    b.Property<int>("ToDoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AnAssignmentID")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Completed")
                        .HasColumnType("INTEGER");

                    b.HasKey("ToDoId");

                    b.HasIndex("AnAssignmentID");

                    b.ToTable("Todo");
                });

            modelBuilder.Entity("MvcStudyBuddy.Api.Models.Todo", b =>
                {
                    b.HasOne("MvcStudyBuddy.Api.Models.Assignment", "AnAssignment")
                        .WithMany()
                        .HasForeignKey("AnAssignmentID");

                    b.Navigation("AnAssignment");
                });
#pragma warning restore 612, 618
        }
    }
}
